version: '3'
services:
  frontend:
    image: public.ecr.aws/r2r2l6v3/arcadia-finance/frontend:v0.0.1
    volumes:
      - /var/www/html/
    hostname: frontend.internal
  backend:
    image: public.ecr.aws/r2r2l6v3/arcadia-finance/backend:v0.0.1
    volumes:
      - /var/www/html/
    hostname: backend.internal
  openbanking:
    image: public.ecr.aws/r2r2l6v3/arcadia-finance/openbanking:v0.0.2
    hostname: openbanking.internal
  nginx:
    image: public.ecr.aws/r2r2l6v3/arcadia-finance/nginx-reverse-proxy:v0.0.2
    ports: 
      - 8080:80
    depends_on:
      - frontend
      - backend
      - openbanking