api_url = "https://treino.console.ves.volterra.io/api"
xc_tenant = "treino-ufahspac"
xc_namespace = "automation-apisec"

project_prefix = "jani-genai"
app_domain = "jbgenai.f5-hyd-xcdemo.com"
serviceName = "langchain-doc-qa-api.llm"
serviceport = "8501"
site_name = "jb-appstack"
user_site = "true"
