#XC Global
api_url = "https://treino.console.ves.volterra.io/api"
xc_tenant = "treino-ufahspac"
xc_namespace = "default"
app_domain = "cek8s.f5-hyd-demo.com"
xc_waf_blocking = "true"
k8s_pool = "true"
serviceName = "productpage.default"
site_name = "ce-k8s"
advertise_sites = "true"
http_only = "true"
