kind: Deployment
apiVersion: apps/v1
metadata:
  name: airline-flask
  annotations:
    ves.io/sites: ves-io-system/sv10-sjc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airline-flask
  template:
    metadata:
      labels:
        app: airline-flask
    spec:
      containers:
        - name: airline-flask
          image: ghcr.io/b3nnnn/airline-flask:latest
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
---
kind: Service
apiVersion: v1
metadata:
  name: airline-flask
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    app: airline-flask
  type: ClusterIP
  sessionAffinity: None
