apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.identity.jwtKeySecret.name }}
  labels:
    release: {{ .Release.Name }}
    {{- with .Values.identity.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{ (.Files.Glob .Values.identity.jwtKeySecret.file).AsSecrets | indent 2 }}
