kind: Namespace
apiVersion: v1
metadata:
  name: az-xcbotdefense-namespace1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: airline-flask
  namespace: az-xcbotdefense-namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airline-flask
  template:
    metadata:
      labels:
        app: airline-flask
    spec:
      containers:
        - name: airline-flask
          image: ghcr.io/b3nnnn/airline-flask:latest
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
      nodeSelector:
        kubernetes.io/os: linux
---
kind: Service
apiVersion: v1
metadata:
  name: airline-flask
  namespace: az-xcbotdefense-namespace1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.248.0.25
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    app: airline-flask
  type: LoadBalancer
  sessionAffinity: None