apiVersion: v1
kind: Service
metadata:
  name: langchain-doc-qa-api
  labels:
    app: langchain-doc-qa-api
  namespace: llm
spec:
  type: ClusterIP
  ports:
  - port: 8501
  selector:
    app: langchain-doc-qa-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-doc-qa-api
  namespace: llm
spec:
  selector:
    matchLabels:
      app: langchain-doc-qa-api
  replicas: 1
  template:
    metadata:
      labels:
        app: langchain-doc-qa-api
    spec:
      containers:
      - name: langchain-doc-qa-api
        image: registry.gitlab.com/f5-public/langchain-docs-summary:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: DOC_PATH
          value: "https://www.f5.com/company/blog/what-is-generative-ai-and-is-it-the-way-to-aiops"
